server:
  port: 8080
  servlet:
    context-path: /node_log

#hbase配置
hbase:
  config:
    #    hbase.zookeeper.quorum: hps13
    hbase.zookeeper.quorum: bigdata1,bigdata2,bigdata3,bigdata4
    #    hbase.zookeeper.quorum: dn1
    hbase.zookeeper.property.clientPort: 2181
    hbase.ipc.server.max.callqueue.size: 1024 * 1024 * 1024
    hbase.hstore.flusher.count: 2
    hbase.hstore.blockingStoreFiles: 10
    client.keyvalue.maxsize: 104857600
    hbase.client.keyvalue.maxsize: -1 # keyvalue 最大值；-1不限制
  time: 864000

data:
  family: log
  table: chenghao_ip_log
  putSize: 100

var:
  log.path: /Users/chenghao/Desktop/log_test
  #  log.path: /Users/chenghao/Desktop/node_test
  cron.date: '0 0 5 * * ?'
  cron.run: true
  loop.batch: 100
  rowkey.splice: ','
  #  每行数据匹配，start
  log.string.txid.start: 'hash='
  log.string.txid.end:
  log.string.ip.start: 'ip='
  log.string.ip.end: ','
  log.string.time.start: 'receivedtime='
  log.string.time.end: 'Z,'
  log.string.ip.addEndIndex: 0
  log.string.txid.addEndIndex: 0
  log.string.time.addEndIndex: 0
  #  每行数据匹配，end
